### ISSUE TITLE
Create downloadables (e.g. the Windows installer) in CI

### ISSUE THREAD

**Issue by dsavenko** [ctuning/ck-crowdnode#10]
CI servers (Travis and Appveyor) should automatically create artifacts on each commit.

**Comment by gfursin** [comment]
And not only - it will be useful to automate this process in general to automatically create an installable release (setup.exe) with correct properties ...

**Comment by gfursin** [comment]
Also related - do you mind to have a look how to create and deploy such apps via Windows Store? I can later register cTuning foundation there (similar to what I did for Google Store) ...

**Comment by dsavenko** [comment]
Sure, I will do it! But this, I guess, should be done manually on major updates only.

**Comment by gfursin** [comment]
Yes, that's right!

**Comment by gfursin** [comment]
By the way, if needed, you can get/create an icon for this app from here:
- https://github.com/ctuning/crowdsource-experiments-using-android-devices/tree/master/app/src/main/res/mipmap-hdpi
