### ISSUE TITLE
server crashes after push command

### ISSUE THREAD

**Issue by gfursin** [ctuning/ck-crowdnode#2]
Hi,
I tested new server on Linux and it accepts push from CK, records file properly, but then crashes with the log (attached). 
[log.txt](https://github.com/ctuning/ck-crowdnode/files/482121/log.txt)
I think it's something with memory allocation/deallocation.
Is it possible to check it please.
To reproduce:
 $ ck add repo:remote-ck-node --url=http://localhost:3333 --remote --quiet
 $ ./ck-crowdnode-server
 $ cat > test.txt
HELLO
 $ ck push remote-ck-node:: --filename=test.txt

Thanks!

P.S. By the way, pull worked and server didn't crash:
$ ck pull remote-ck-node:: --filename=test.txt

**Comment by DVEfremov** [comment]
Fixed at commit ffe5a715cd77f04a8ff5858873914a347a59ef83

**Comment by gfursin** [comment]
Seems to be working! Thanks!
