### ISSUE TITLE
big file was not recorded properly during push

### ISSUE THREAD

**Issue by gfursin** [ctuning/ck-crowdnode#3]
Tried to push relatively large binary file (700Kb). I could see that server prints lots of incoming stuff (seems correct, by the way, it's better probably to put a limit on print of long key, i.e. < 256 bytes), but recorded only 90 bytes ... Interestingly, server didn't crash this time at the end (see #1) and even returned 'ok'...

Is is possible to test it too, please?

Thanks!

**Comment by DVEfremov** [comment]
I've checked the process step by step:
1) I've got  test_file5 for test
$ ls -l test_file5 
-rw-rw-r-- 1 daniil daniil 425889 Sep 20 19:16 test_file5
2) run ck push remote-ck-node:: --filename=test_file5

4) got encoded end of the file at post data: 
...gZHVtcCBjb21wbGV0ZQotLQoK%22%2C+%22action%22%3A+%22push%22%2C+%22cids%22%3A+%5B%5D%2C+%22out%22%3A+%22con%22%7D

5) Same end of url decoded JSON (I've compared whole content as well it's the same):
"file_content_base64":"LS0KLS0gUG9zdGdy...gZHVtcCBjb21wbGV0ZQotLQoK", "action": "push", "cids": [], "out": "con"}

6) I'v tried to decode manually value of provided file_content_base64
$ base64 -d file_content_base64 > file_content
base64: invalid input
$ ls -l file_content
-rw-rw-r-- 1 daniil daniil 30038 Sep 21 09:09 file_content
same size and content as pushed to /tmp/test_file5

so now I see I've got already cut encoded file content at post data marameter ck_json.

So looking into ck push function to find bug ...

**Comment by DVEfremov** [comment]
I've printed encoded file at  ck/ck/kernel.py:
    s=base64.urlsafe_b64encode(s).decode('utf8')
    # my debug print out string:
    print s

And got at out put 
$ck push remote-ck-node:: --filename=test_file5 > ck.out
same cut encoded message already:
...c3RncmVTUUwgZGF0YWJhc2UgZHVtcCBjb21wbGV0ZQotLQoK

But file before encode completely loaded (I've got this from printed "s" value as well)

**Comment by gfursin** [comment]
I now print length of data in the crowdnode server and it's correct.
CK encodes fine - we use this encoding function in all our push/pull files including Android app, various services, etc, and it's compatible with Java implementation (I have checked that before).
HOWEVER, when implementing encoding function, I noticed that there are several standards, and there were recent enhancements to this standard, so old mime functions do not work (I saw it with Java).
You are using C lib from 2003 - I guess it's simply outdated. Can you please search for a newer one
(i.e. the one that will process CK's encoded string correctly) - I saw many discussions on internet about this standard, so I am sure there is something available... Or maybe search for compatible encode function specifically between Python and C ...
BTW, I also added tests directory with _push.sh script ... 
Thanks!

**Comment by DVEfremov** [comment]
Yes correct. There are different base64 encoding algorithms and Python uses URL safe RFC 3548 version. I've used MIME (RFC 1421) version. 
So I've fixed and checked push and pull works now. 
Later I''ll  try to reproduce my original problem with exact file witch does not come completely for some reason (any way it's out of scope and can be tracked separately)

**Comment by gfursin** [comment]
Yeap, it's working now! Thanks! I close this ticket!
