### ISSUE TITLE
make this node compile and run on Windows

### ISSUE THREAD

**Issue by gfursin** [ctuning/ck-crowdnode#4]
I tried to make it compatible with Windows build system (using my 10-years old scripts when I did some client/servers on Windows via socket), but it's not yet working. Need help to finalize it! Thanks!

**Comment by DVEfremov** [comment]
I've implemented UID Generation in scope of this issue at Commit f5d02ae as well

**Comment by gfursin** [comment]
I did a few minor fixes for Windows. Server starts and receives commands. However, I do not have directory C:\Tmp, so server crashes when I try to push file. I guess this will be fixed with the configuration file (issue #5) and detection of %Temp% directory on Windows (when setting default configuration). However, it is still useful not to crash with seg fault, if there is a problem with writing. 

When adding C:\Tmp, it starts working and file is pushed correctly, However the returned string is not recognized by CK (I think it has '\n' as string rather than character), so I receive the following error:

CK error: Access to remote CK repository failed ({
)!

Is it possible to check that the returned string on Windows has '\n' as character, please (I think this is the problem)?

Thanks a lot!

**Comment by DVEfremov** [comment]
> Is it possible to check that the returned string on Windows has '\n' as character, please (I think this is >the problem)?

There is the same result message format build  with 
`cJSON_Print(resultJSON)`

But  I noticed that "pull" command process result string without issue 
"push"  just print response as is: 

`{
 "return": "0",
 "compileUUID": "39a9e854-8496-11e6-8029-912d40471f21"
}
`

**Comment by DVEfremov** [comment]
> However, I do not have directory C:\Tmp, so server crashes when I try to push file
> fixed at commit 1f1a7d5

**Comment by DVEfremov** [comment]
I've added dummy "shell" command implementation at commit efd8bea. 
It could be used now to check if command result is ok.
Command  example:
`call ck shell remote-ck-node:: --filename=ck-master.zip  --secretkey=c4e239b4-8471-11e6-b24d-cbfef11692ca --cmd="echo \"test\""`

result message:
`{
 "return": "0",
 "return_code": 0,
 "stdout": "some program std out",
 "stderr": "some program stderr"
}
`

**Comment by gfursin** [comment]
This looks fine. But just curious - you do not need "--filename" here, right?

**Comment by DVEfremov** [comment]
> This looks fine. But just curious - you do not need "--filename" here, right?

Yes for sure will remove from example in next commit

**Comment by gfursin** [comment]
It's now working on Windows - thanks a lot!!!
