### ISSUE TITLE
adding configuration file

### ISSUE THREAD

**Issue by gfursin** [ctuning/ck-crowdnode#5]
It will be useful to add reading of the configuration file 'ck-crowdnode-config.json' when server starts. 

On Linux we can keep it in '$HOME/.ck-crowdnode/ck-crowdnode-config.json'.
On Windows we may keep it in %LOCALAPPDATA%.ck-crowdnode\ck-crowdnode-config.json (see https://blogs.msdn.microsoft.com/patricka/2010/03/18/where-should-i-store-my-data-and-configuration-files-if-i-target-multiple-os-versions/)

If it doesn't exist at first run, we can create it with the following default config:

Current config should have:
{
 'port':3333,
 'path_to_files':'/tmp/ck-crowdnode'
}

Or on Windows, it will likely be %Temp%\ck-crowdnode

Also at run we should check that this directory exists and create it otherwise.

path_to_files is where we push/pull/execute files 

We can then add a new command 'status' which returns
{ 'return':0,
 'path_to_files":...
}

This will allow us to query server and check that it works fine ...

**Comment by DVEfremov** [comment]
I've also add _compile_and_run_with_valgrind.sh
and fixed some detected problems.
It's useful for future memory leak profiling if "valgrind" installed.
For ubuntu "valgrind"  could be installed with command: 
  `sudo apt-get install valgrind`

**Comment by DVEfremov** [comment]
Now server loads port number and base file dir from configuration file located at:
-   "%LOCALAPPDATA%/.ck-crowdnode/ck-crowdnode-config.json" for windows
-   "$HOME/.ck-crowdnode/ck-crowdnode-config.json" for linux

File example for win:
`
    {"port":3334, "path_to_files":"%LOCALAPPDATA%/ck-crowdnode"}
`
  if configurration file does not exist default configuration will be set:
-    port=3333,
-    path_to_files="%LOCALAPPDATA%/ck-crowdnode"

**Comment by DVEfremov** [comment]
I've added default config file creation if doesn't not exist
- for windows: "%LOCALAPPDATA%/.ck-crowdnode/ck-crowdnode-config.json"
- for linux: "$HOME/.ck-crowdnode/ck-crowdnode-config.json"

and default dir for ck files as well 
- for windows: "%LOCALAPPDATA%/ck-crowdnode-files/"
- for linux: "$HOME/ck-crowdnode-files/"

**Comment by gfursin** [comment]
This all seems to be working fine now. Thanks!
