### ISSUE TITLE
Adding secret_key file ...

### ISSUE THREAD

**Issue by gfursin** [ctuning/ck-crowdnode#6]
One more thing - we should add some basic security for now (I expect that if prototype is accepted, we or someone else can provide much stronger security).

Whenever ANY command is passed to server, you need to check if a 'secret_key' string is present in config file (#5), and if it's !='', compare it with the 'secret_key' in the input JSON, and quit if they are not the same:
{
 'return':3,
 'error':'secret keys do not match'
}

Thanks a lot!

**Comment by gfursin** [comment]
Actually, if such key doesn't exist, is it possible to just generate a UID and print it. Or if it's there, when you start a server, you can print it. Whenever a remote user needs to add such remote device, they need to know and add such key in a client (a bit like in android tethering) ...

**Comment by DVEfremov** [comment]
Fixed but with invalid JSON format nadling for configuration file.
Add new parameter "secret_key" to configuration file implemented at #5
- if parameter not provided new secret key value will be generated based on UUID generator and printed to server output, example: 
  `[WARN]: CK-crowdnode-server configuration file problem. Server will be started with default configuration, port: 3333, pathToFiles: /tmp/, secret_key: 4fd4b4c4-847d-11e6-8eb1-e3e9eb7ebf5f
  `
- for all commands parameter secretkey must be defined now, example:
  call ck push remote-ck-node:: --filename=ck-master.zip -secretkey=c4e239b4-8471-11e6-b24d-cbfef11692ca

**Comment by gfursin** [comment]
Seems to be working fine! Thanks!
