### ISSUE TITLE
extra improvements

### ISSUE THREAD

**Issue by gfursin** [ctuning/ck-crowdnode#9]
I managed to create a distro (setup.exe) and run it on a remote machine. A few small things that needs to be added to the server:
- We need to print real IP (i.e. not 127.0.0.1, but something like 192.168.1.64 on local or 186.xx.yy.zz on real network)... 
  [INFO for CK client]: real IP: xyz
  This is needed to set up CK machine (otherwise I need to check IP via ipconfig)
- When executing cmd (shell), we should change current directory to "path to files", before executing it!

Thanks!

**Comment by gfursin** [comment]
Seems to be working fine! Thanks a lot! Just couple of more changes not to forget:
- we need to use correct slash (/ on Linux or \ on Windows), which we can do via #define
- is it possible to generate shorter secret keys - for example use part of CK UID (8 hexadecimal) - otherwise it's very long and complex to write for users - for now it's a weak security - we can make it stronger later ...

**Comment by DVEfremov** [comment]
> we need to use correct slash (/ on Linux or \ on Windows), which we can do via #define

fixed at commit 580246093535496dfdf47901494f4e54fbf9fe80

**Comment by DVEfremov** [comment]
> is it possible to generate shorter secret keys - for example use part of CK UID (8 hexadecimal) - >otherwise it's very long and complex to write for users - for now it's a weak security - we can make it ?>stronger later ...

fixed at commit f05f2c92798518a25e80fd52062ac4b4c763e353

**Comment by gfursin** [comment]
All updates seems to be working fine! Thanks! I close this ticket!
